language: go

install:
    - git clone --branch v0.59.1 --depth 1 https://github.com/gohugoio/hugo.git hugo
    - cd hugo
    - go clean -modcache
    - go install

script:
    - hugo

deploy:
    provider: pages
    skip_cleanup: true
    on:
        branch: master

    github_token: $GITHUB_TOKEN
    repo: edoren/edoren.github.io
    local_dir: public/
    target_branch: master
    fqdn: edoren.me
