language: go
go: 1.8

install:
    - go get github.com/spf13/hugo
    - go get github.com/wellington/wellington/wt

script:
    - wt compile static/scss/ --build static/css/ --style=compressed
    - hugo
    - rm -r public/scss

deploy:
    provider: pages
    skip_cleanup: true
    on:
        branch: master

    github_token: $GITHUB_TOKEN
    repo: edoren/edoren.github.io
    local_dir: public/
    target_branch: master
    fqdn: edoren.me
