baseurl: http://edoren.me/
title: Manuel Sabogal
languageCode: en-us
MetaDataFormat: yaml

blackfriday:
    hrefTargetBlank: true

taxonomies:
    tag: tags
    category: categories

author:
    name: Manuel Sabogal
    email: mfer32@gmail.com
    github: edoren
    gitlab: edoren
    twitter: ItsEdoren
    linkedin: edoren

params:
    description: Software Development

    highlight: monokai-sublime

    disqusShortname: edoren
    googleAnalytics: UA-49027257-3
    gravatarHash: fc2e213fc8d2758e7e35017ddd0e2566

    navlinks:
        - name: Blog
          url: blog/
        - name: About
          url: about/
