baseURL: https://edoren.me/
title: Manuel Sabogal
languageCode: en-us
enableGitInfo: true

languages:
  en:
    weight: 1
    languageName: English
    params:
        description: Software Development
  es:
    weight: 2
    languageName: Español
    params:
        description: Desarrollo de Software

blackfriday:
    hrefTargetBlank: true

taxonomies:
    tag: tags
    category: categories


params:
    buildVersion: master

    disqusShortname: edoren
    googleAnalytics: UA-49027257-3
    gravatarHash: fc2e213fc8d2758e7e35017ddd0e2566

    navlinks:
        - blog
        - about

    author:
        first_name: Manuel
        last_name: Sabogal
        full_name: Manuel Sabogal
        email: mfer32@gmail.com
        twitter: ItsEdoren
        github: edoren
        gitlab: edoren
        linkedin: edoren

markup:
    highlight:
        codeFences: false
