baseURL: https://edoren.me/
title: Manuel Sabogal
languageCode: en-us
enableGitInfo: true

languages:
  en:
    weight: 1
    languageName: English
    description: Software Development
  es:
    weight: 2
    languageName: Español
    description: Desarrollo de Software

blackfriday:
    hrefTargetBlank: true

taxonomies:
    tag: tags
    category: categories

author:
    first_name: Manuel
    last_name: Sabogal
    full_name: Manuel Sabogal
    email: mfer32@gmail.com
    twitter: ItsEdoren
    github: edoren
    gitlab: edoren
    linkedin: edoren

params:
    buildVersion: master

    highlight: monokai-sublime

    disqusShortname: edoren
    googleAnalytics: UA-49027257-3
    gravatarHash: fc2e213fc8d2758e7e35017ddd0e2566

    navlinks:
        - blog
        - about
